#ifndef A1_DISPLAY_H
#define A1_DISPLAY_H

#include <stdbool.h>

enum {
    A1_DISPLAY_LOOP_INTERVAL_MS = 50,
    A1_DISPLAY_BLUETOOTH_POLL_MS = 500,
    A1_DISPLAY_CHARGING_POLL_MS = 1000,
    A1_DISPLAY_AUTO_RETURN_MS = 3000,
    A1_DISPLAY_CHARGING_REFRESH_MS = 30000
};

typedef enum {
    A1_DISPLAY_BOOT_ANIMATION = 7,
    A1_DISPLAY_ACTIVATION_REMIND = 8,
    A1_DISPLAY_BT_ACTIVATING = 9,
    A1_DISPLAY_ACTIVATION_SUCCESS = 10,
    A1_DISPLAY_ACTIVATION_FAILED = 11,
    A1_DISPLAY_STANDBY_WELCOME = 14,
    A1_DISPLAY_PRESS_RELEASE_REMIND = 16,
    A1_DISPLAY_BATTERY_LOW_10 = 17,
    A1_DISPLAY_BATTERY_LOW_2_SHUTTING_DOWN = 18,
    A1_DISPLAY_WIFI_TRANSFER_FINISHED = 22,
    A1_DISPLAY_RECORDING = 24,
    A1_DISPLAY_RECORD_PAUSED = 25,
    A1_DISPLAY_RECORD_STOP = 27,
    A1_DISPLAY_SYNCING = 29,
    A1_DISPLAY_SYNC_COMPLETE = 30,
    A1_DISPLAY_SYNC_FAILED = 31,
    A1_DISPLAY_CHARGING = 37,
    A1_DISPLAY_LISTENING_ANIM = 38,
    A1_DISPLAY_VOICE_MEMO_ANIM = 39,
    A1_DISPLAY_VOICEPRINT_ANIM = 40,
    A1_DISPLAY_DEVICE_UPGRADING = 41
} a1_display_state_t;

const char *a1_display_state_name(int state);
bool a1_display_state_is_transient(int state);
int a1_display_auto_return_target(
    int state,
    int normal_return_state,
    bool charging);

#endif
